apiVersion: v1
kind: Secret
metadata:
  name: mysql-creds
  namespace: mysql
type: Opaque
data:
  mysql-pass: QWRtaW4xMjMhJQ==
  mysql-user: YWRtaW4=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfig
  namespace: wordpress
data:
  mysqldbname: "mysqldb"