apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: ristabel/mysql:v1
        ports:
        - name: mysql-port
          containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: mysql-pass
        - name: MYSQL_HOST
          value: "localhost"  # Use "localhost" for local MySQL
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  
spec:
  storageClassName: ebs-sc  # Replace with your EFS storage class
  resources:
    requests:
      storage: 100Mi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp2  # Use the desired EBS volume type (e.g., gp2 for General Purpose SSD)
reclaimPolicy: Retain
allowVolumeExpansion: true

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mysql-access
  namespace: mysql
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
    - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app: wordpress
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wordpress-pod-reader
  namespace: mysql
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpress-pod-reader-binding
  namespace: mysql
subjects:
- kind: ServiceAccount
  name: default
  namespace: wordpress
roleRef:
  kind: Role
  name: wordpress-pod-reader
  apiGroup: rbac.authorization.k8s.io

